spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/dp_app
    password: dexter
  application:
    name: ioc
  mvc:
    problem-details:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to Dexter Code!!!
server:
  port: '8082'
